# This is a basic workflow to help you get started with Actions

name: CI For dockerised Flask app

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]



# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a 2 jobs 
  build-and-test: # JOB1
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout code
        uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: set up python
        run: actions/setup-python
        with:
          python-version: '3.9'

      # Runs a set of commands using the runners shell
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip,
          python install flask
          python install pytest

      - name: Run test
        run: |
          pytest

  build-and-publish: # JOB2
    needs: build and test
    runs-on: ubuntu-latest

    steps:
     - name: checkout code
       uses: actions/checkout@v3     

     - name: Set up Docker Buildx
       uses: docker/setup-buildx-action@v2  
     
     - name: Login to DockerHub
       uses: docker/login-actions@v2
       with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

     - name: Build and push docker image
       uses: docker/build-push-action@v4
       with:
        context: 
          file: ./DockerFile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/flasktest-app:latest  

     - name: Image digest
       run: echo ${{ steps.build-and-publish.outputs.digest }}      